#覆盖访问路径
server:
  servlet:
    context‐path: /merchant-application

#启用Swagger
#http://localhost:57010/merchant-application/swagger-ui.html
swagger:
  enable: true

#验证码服务
sms:
  url: "http://localhost:56085/sailing" #验证码服务地址
  effectiveTime: 600 #验证码过期时间

#七牛云
oss:
  qiniu:
    url: "r32uoy595.hn-bkt.clouddn.com"
    accessKey: "fS5HOgFJTbtBlUqhSca0j8QxC3ixtlm6-NY2O4jn"
    secretKey: "vNFfcw5uhA_YvP4AnPCBxf5qG0N_-Z16isEnTmBH"
    bucket: "shanjupay-hqz211124"